swiftmailer:
    url: '%env(MAILER_URL)%'
    transport: gmail
    username: 'issadevtest@gmail.com'
    password: 'Shyrone59'
    port: 465
    encryption: ssl
    auth_mode: login
    spool: { type: 'memory' }